window.DEEP_THEORY_ITEMS = [
  {
    id: "deep-req-001",
    heat: "MAX",
    title: "기능 요구사항과 비기능 요구사항",
    oneLine: "기능 요구사항은 '무엇을 할까', 비기능 요구사항은 '얼마나 잘할까'다.",
    why: "요구사항 문제는 말장난처럼 보이지만, 기능/비기능만 나누면 대부분 풀린다.",
    memorize: "로그인한다=기능. 3초 안에 로그인한다=비기능. 암호화한다=비기능.",
    example: "회원가입, 상품검색, 결제는 기능이다. 성능, 보안, 가용성, 신뢰성은 비기능이다.",
    linked: "요구사항 문제가 나오면 문장 끝을 보고 '행동'인지 '품질 조건'인지 먼저 나눈다.",
    tags: ["요구사항", "기능", "비기능"],
  },
  {
    id: "deep-req-002",
    heat: "HIGH",
    title: "요구사항 개발 절차",
    oneLine: "요구사항은 도출, 분석, 명세, 확인 순서로 정리한다.",
    why: "순서 문제가 자주 나온다. 말만 어려울 뿐 회의해서 뽑고, 정리하고, 문서화하고, 맞는지 보는 것이다.",
    memorize: "도분명확. 도출, 분석, 명세, 확인.",
    example: "고객 인터뷰로 요구를 도출하고, 충돌을 분석하고, 요구사항 명세서에 쓰고, 고객에게 맞는지 확인한다.",
    linked: "절차 문제는 첫 글자만 외운 뒤 문맥에 끼워 넣는다.",
    tags: ["요구사항", "절차", "명세"],
  },
  {
    id: "deep-req-003",
    heat: "MID",
    title: "요구사항 추적성",
    oneLine: "추적성은 요구사항이 설계, 코드, 테스트까지 제대로 이어졌는지 따라가는 능력이다.",
    why: "변경 영향 분석 문제에서 자주 쓰인다. 요구사항 하나가 바뀌면 어디까지 고쳐야 하는지 알아야 한다.",
    memorize: "요구가 바뀌면 따라가야 한다. 그래서 추적성.",
    example: "로그인 보안 요구사항이 바뀌면 화면, API, DB, 테스트 케이스가 함께 바뀔 수 있다.",
    linked: "추적성은 '연결', '영향', '변경'이라는 말이 나오면 떠올린다.",
    tags: ["요구사항", "추적성", "변경"],
  },
  {
    id: "deep-ui-001",
    heat: "MID",
    title: "UI와 UX",
    oneLine: "UI는 화면 그 자체, UX는 사용자가 느끼는 전체 경험이다.",
    why: "UI/UX는 쉬운 단답이지만 헷갈리면 점수를 잃는다.",
    memorize: "UI는 버튼과 화면, UX는 편한가 불편한가.",
    example: "검색 버튼 위치는 UI다. 검색이 빨라서 편하다고 느끼는 것은 UX다.",
    linked: "화면 설계 문제는 UI 산출물 이름을 같이 외운다.",
    tags: ["UI", "UX", "화면설계"],
  },
  {
    id: "deep-ui-002",
    heat: "MID",
    title: "와이어프레임, 스토리보드, 프로토타입",
    oneLine: "와이어프레임은 뼈대, 스토리보드는 화면 흐름 설명서, 프로토타입은 시험용 모형이다.",
    why: "세 단어를 섞어 내는 문제가 나온다.",
    memorize: "뼈대=와이어프레임, 이야기=스토리보드, 미리 만들어봄=프로토타입.",
    example: "버튼 위치만 대충 그린 것은 와이어프레임, 화면 전환과 설명이 붙으면 스토리보드다.",
    linked: "문제에서 '동작 가능한 모형'이라면 프로토타입을 고른다.",
    tags: ["UI", "와이어프레임", "프로토타입"],
  },
  {
    id: "deep-uml-001",
    heat: "HIGH",
    title: "UML 기본",
    oneLine: "UML은 소프트웨어 구조와 행동을 그림으로 표현하는 표준 언어다.",
    why: "유스케이스, 클래스, 시퀀스, 활동 다이어그램이 단답으로 자주 나온다.",
    memorize: "사용자 기능=유스케이스, 클래스 구조=클래스, 메시지 순서=시퀀스, 흐름=활동.",
    example: "사용자와 시스템 기능을 타원으로 그리면 유스케이스 다이어그램이다.",
    linked: "다이어그램 문제는 '무엇을 보여주는 그림인가'만 찾는다.",
    tags: ["UML", "설계", "다이어그램"],
  },
  {
    id: "deep-uml-002",
    heat: "HIGH",
    title: "클래스 다이어그램",
    oneLine: "클래스 다이어그램은 클래스 이름, 속성, 메서드, 클래스 사이 관계를 보여준다.",
    why: "객체지향 설계와 함께 나와서 상속, 연관, 집합, 합성 관계를 묻는다.",
    memorize: "클래스 그림은 '누가 누구를 갖고, 누가 누구를 상속하나'를 보는 그림.",
    example: "학생 클래스가 이름과 학번 속성을 가지고, 수강신청 메서드를 갖는 식이다.",
    linked: "UML 문제에서 속성/메서드/관계가 나오면 클래스 다이어그램을 떠올린다.",
    tags: ["UML", "클래스", "객체지향"],
  },
  {
    id: "deep-design-001",
    heat: "HIGH",
    title: "응집도",
    oneLine: "응집도는 모듈 안의 코드들이 한 가지 일에 얼마나 잘 모여 있는가다.",
    why: "응집도는 높을수록 좋고, 결합도는 낮을수록 좋다는 원칙이 자주 나온다.",
    memorize: "좋은 응집도는 기능적, 나쁜 응집도는 우연적.",
    example: "회원 로그인만 처리하는 모듈은 응집도가 높고, 로그인/결제/출력을 다 하면 낮다.",
    linked: "응집도 순서 문제는 '기능적'이 최고라는 것부터 잡는다.",
    tags: ["설계", "응집도", "모듈"],
  },
  {
    id: "deep-design-002",
    heat: "HIGH",
    title: "결합도",
    oneLine: "결합도는 모듈끼리 얼마나 서로 얽혀 있는가다.",
    why: "결합도는 낮을수록 수정이 쉽고 장애 전파가 줄어든다.",
    memorize: "자료 결합이 좋고, 내용 결합이 나쁘다.",
    example: "함수에 필요한 값만 인자로 넘기면 결합도가 낮고, 다른 모듈 내부 변수를 직접 건드리면 높다.",
    linked: "모듈 독립성 문제는 응집도 높게, 결합도 낮게가 답이다.",
    tags: ["설계", "결합도", "모듈"],
  },
  {
    id: "deep-design-003",
    heat: "MID",
    title: "객체지향 3대 특징",
    oneLine: "캡슐화, 상속, 다형성은 객체지향의 기본 뼈대다.",
    why: "Java 코드와 설계 이론이 같이 나올 때 필요하다.",
    memorize: "감춘다=캡슐화, 물려받는다=상속, 같은 이름 다른 행동=다형성.",
    example: "부모 타입 변수로 자식 객체의 오버라이딩 메서드를 호출하면 다형성이 보인다.",
    linked: "Java 문제와 디자인 패턴 문제의 바탕 이론이다.",
    tags: ["객체지향", "Java", "설계"],
  },
  {
    id: "deep-pattern-001",
    heat: "MAX",
    title: "Singleton 패턴",
    oneLine: "Singleton은 객체를 딱 하나만 만들어 모두가 같이 쓰게 하는 패턴이다.",
    why: "2022~2026 공개 복원 범위에서 패턴 단답이 반복된다.",
    memorize: "하나만 있어야 하면 Singleton.",
    example: "프로그램 전체 설정 객체, 로그 관리자처럼 하나만 있으면 되는 것에 쓴다.",
    linked: "패턴 문제는 이름보다 '의도'를 보고 맞힌다.",
    tags: ["디자인패턴", "Singleton", "생성패턴"],
  },
  {
    id: "deep-pattern-002",
    heat: "MAX",
    title: "Observer 패턴",
    oneLine: "Observer는 어떤 객체 상태가 바뀌면 구독자들에게 자동으로 알려주는 패턴이다.",
    why: "상태 변화, 통지, 구독이라는 말이 나오면 거의 Observer다.",
    memorize: "유튜브 구독 알림을 떠올려라. 바뀌면 알려준다.",
    example: "뉴스 앱에서 새 기사가 뜨면 구독자 화면이 자동 갱신되는 구조다.",
    linked: "알림/통지/구독이라는 단어를 찾는다.",
    tags: ["디자인패턴", "Observer", "행위패턴"],
  },
  {
    id: "deep-pattern-003",
    heat: "HIGH",
    title: "Iterator 패턴",
    oneLine: "Iterator는 내부 구조를 몰라도 하나씩 순서대로 꺼내 보게 해주는 패턴이다.",
    why: "컬렉션, 순차 접근, 반복자라는 말이 나오면 답이 된다.",
    memorize: "리스트 속을 몰라도 다음 것 next로 꺼낸다.",
    example: "배열이든 리스트든 같은 방식으로 하나씩 순회하게 만든다.",
    linked: "순회/반복/내부구조 은닉 문제에서 고른다.",
    tags: ["디자인패턴", "Iterator", "행위패턴"],
  },
  {
    id: "deep-pattern-004",
    heat: "HIGH",
    title: "Bridge 패턴",
    oneLine: "Bridge는 기능 계층과 구현 계층을 분리해서 서로 따로 바꿀 수 있게 한다.",
    why: "추상화와 구현 분리라는 문장이 나오면 Bridge가 정답일 가능성이 높다.",
    memorize: "다리처럼 두 세계를 연결한다. 기능과 구현을 분리 연결.",
    example: "리모컨 기능과 TV 제조사 구현을 분리하면 리모컨도 TV도 따로 확장할 수 있다.",
    linked: "분리, 독립 확장, 추상화와 구현이라는 말을 찾는다.",
    tags: ["디자인패턴", "Bridge", "구조패턴"],
  },
  {
    id: "deep-db-001",
    heat: "MAX",
    title: "DB 스키마 3계층",
    oneLine: "외부 스키마는 사용자 화면, 개념 스키마는 전체 구조, 내부 스키마는 저장 방법이다.",
    why: "스키마 3계층은 정의형 단답으로 나온다.",
    memorize: "밖에서 보는 것=외부, 전체 설계도=개념, 디스크 저장=내부.",
    example: "학생은 자기 성적 화면만 보지만, 학교 DB 전체 구조는 개념 스키마에 해당한다.",
    linked: "DB 이론 문제에서 사용자 관점/전체 관점/저장 관점을 나눈다.",
    tags: ["DB", "스키마", "3계층"],
  },
  {
    id: "deep-db-002",
    heat: "HIGH",
    title: "무결성",
    oneLine: "무결성은 DB 데이터가 틀리지 않고 규칙을 지키는 상태다.",
    why: "개체 무결성, 참조 무결성, 도메인 무결성이 자주 나온다.",
    memorize: "기본키 NULL 금지=개체, 외래키 참조 지킴=참조, 값 범위 지킴=도메인.",
    example: "나이가 -3이면 도메인 무결성 위반이다. 없는 학번을 외래키로 쓰면 참조 무결성 위반이다.",
    linked: "키와 제약조건 문제와 함께 본다.",
    tags: ["DB", "무결성", "제약조건"],
  },
  {
    id: "deep-db-003",
    heat: "HIGH",
    title: "ERD",
    oneLine: "ERD는 개체, 관계, 속성을 그림으로 표현한 데이터 설계도다.",
    why: "개체집합, 관계집합, 속성 같은 단어가 반복된다.",
    memorize: "사각형=개체, 마름모=관계, 타원=속성.",
    example: "학생이 과목을 수강한다면 학생과 과목은 개체, 수강은 관계다.",
    linked: "개체/관계/속성 구분 문제에서 바로 쓴다.",
    tags: ["DB", "ERD", "개체관계"],
  },
  {
    id: "deep-db-004",
    heat: "MAX",
    title: "함수 종속",
    oneLine: "X를 알면 Y가 하나로 정해질 때 Y는 X에 함수 종속이다.",
    why: "정규화의 핵심 이유가 함수 종속이다.",
    memorize: "학번을 알면 이름이 정해진다. 이름은 학번에 종속.",
    example: "학번 -> 이름, 학번 -> 학과처럼 왼쪽이 결정자다.",
    linked: "정규화 문제는 함수 종속 화살표를 먼저 본다.",
    tags: ["DB", "함수종속", "정규화"],
  },
  {
    id: "deep-db-005",
    heat: "MAX",
    title: "1NF, 2NF, 3NF, BCNF",
    oneLine: "정규형은 테이블을 얼마나 깔끔하게 쪼갰는지 보는 단계다.",
    why: "부분 종속과 이행 종속을 제거하는 단계는 정말 자주 나온다.",
    memorize: "1NF 원자값, 2NF 부분 종속 제거, 3NF 이행 종속 제거, BCNF 모든 결정자가 후보키.",
    example: "A->B, B->C이면 A->C가 생기는 이행 종속이므로 3NF에서 분리한다.",
    linked: "문장에 부분이 나오면 2NF, 이행이 나오면 3NF.",
    tags: ["DB", "정규형", "정규화"],
  },
  {
    id: "deep-db-006",
    heat: "HIGH",
    title: "이상 현상",
    oneLine: "이상 현상은 테이블 설계가 나빠서 삽입, 삭제, 갱신 때 이상한 문제가 생기는 것이다.",
    why: "정규화가 필요한 이유를 묻는 문제에서 나온다.",
    memorize: "삽입 이상, 삭제 이상, 갱신 이상.",
    example: "과목을 아직 듣는 학생이 없어서 과목 정보를 넣을 수 없다면 삽입 이상이다.",
    linked: "정규화와 항상 묶어서 본다.",
    tags: ["DB", "이상현상", "정규화"],
  },
  {
    id: "deep-db-007",
    heat: "HIGH",
    title: "인덱스",
    oneLine: "인덱스는 책의 목차처럼 데이터를 빨리 찾게 해주는 구조다.",
    why: "장점과 단점이 동시에 나오는 단답형 이론이다.",
    memorize: "조회 빠름, 저장공간 사용, 삽입/삭제/수정은 느려질 수 있음.",
    example: "이름으로 자주 검색하는 회원 테이블에 이름 인덱스를 만들 수 있다.",
    linked: "성능 향상이라는 말만 보고 무조건 좋은 것으로 착각하지 않는다.",
    tags: ["DB", "인덱스", "성능"],
  },
  {
    id: "deep-db-008",
    heat: "MID",
    title: "뷰",
    oneLine: "뷰는 실제 테이블을 바탕으로 만든 가짜 테이블 같은 것이다.",
    why: "보안, 편의성, 논리적 독립성 문제로 나온다.",
    memorize: "저장은 가짜, 조회는 테이블처럼.",
    example: "직원 테이블에서 이름과 부서만 보이게 하는 직원조회 뷰를 만들 수 있다.",
    linked: "보안과 조회 편의성 키워드가 나오면 뷰를 떠올린다.",
    tags: ["DB", "뷰", "보안"],
  },
  {
    id: "deep-sql-001",
    heat: "MAX",
    title: "SQL 분류",
    oneLine: "DDL은 구조, DML은 데이터, DCL은 권한, TCL은 트랜잭션이다.",
    why: "명령어를 분류하는 문제는 무조건 맞혀야 한다.",
    memorize: "CREATE/ALTER/DROP=DDL, SELECT/INSERT/UPDATE/DELETE=DML, GRANT/REVOKE=DCL, COMMIT/ROLLBACK=TCL.",
    example: "테이블을 만드는 CREATE는 DDL이고, 값을 넣는 INSERT는 DML이다.",
    linked: "SQL 문제를 풀기 전에 명령어가 어느 분류인지 먼저 본다.",
    tags: ["SQL", "DDL", "DML"],
  },
  {
    id: "deep-sql-002",
    heat: "MAX",
    title: "SELECT 실행 흐름",
    oneLine: "SELECT문은 FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY 흐름으로 생각하면 쉽다.",
    why: "WHERE와 HAVING을 구분하는 문제가 반복된다.",
    memorize: "WHERE는 그룹 전 행 조건, HAVING은 그룹 후 조건.",
    example: "학과별 평균 점수가 80 이상인 학과를 찾을 때 평균 조건은 HAVING에 둔다.",
    linked: "집계 함수가 조건에 나오면 HAVING을 의심한다.",
    tags: ["SQL", "SELECT", "HAVING"],
  },
  {
    id: "deep-sql-003",
    heat: "MAX",
    title: "집계 함수",
    oneLine: "COUNT, SUM, AVG, MAX, MIN은 여러 행을 하나의 값으로 요약한다.",
    why: "결과 행 수와 중복 제거 문제가 자주 나온다.",
    memorize: "개수 COUNT, 합계 SUM, 평균 AVG, 최대 MAX, 최소 MIN.",
    example: "COUNT(DISTINCT DEPT)는 서로 다른 학과의 개수를 센다.",
    linked: "DISTINCT가 COUNT 안에 있으면 값 종류 수를 세는 것이다.",
    tags: ["SQL", "집계", "COUNT"],
  },
  {
    id: "deep-sql-004",
    heat: "HIGH",
    title: "JOIN",
    oneLine: "JOIN은 두 테이블을 관련 있는 컬럼 기준으로 붙이는 것이다.",
    why: "INNER JOIN, OUTER JOIN, NATURAL JOIN이 결과 해석으로 나온다.",
    memorize: "INNER는 맞는 것만, OUTER는 안 맞아도 살림, NATURAL은 같은 이름 컬럼 자동 연결.",
    example: "학생 테이블과 성적 테이블을 학번으로 연결하면 학생별 성적을 볼 수 있다.",
    linked: "두 테이블이 나오면 연결 기준 컬럼을 먼저 찾는다.",
    tags: ["SQL", "JOIN", "DB"],
  },
  {
    id: "deep-sql-005",
    heat: "HIGH",
    title: "제약조건",
    oneLine: "제약조건은 DB에 이상한 값이 들어오지 못하게 막는 규칙이다.",
    why: "PRIMARY KEY, FOREIGN KEY, UNIQUE, NOT NULL, CHECK가 빈칸으로 나온다.",
    memorize: "대표키 PRIMARY KEY, 참조키 FOREIGN KEY, 중복금지 UNIQUE, NULL금지 NOT NULL, 조건검사 CHECK.",
    example: "나이가 0 이상이어야 한다면 CHECK(age >= 0)를 걸 수 있다.",
    linked: "CONSTRAINT와 REFERENCES 철자를 정확히 외운다.",
    tags: ["SQL", "제약조건", "키"],
  },
  {
    id: "deep-sql-006",
    heat: "MID",
    title: "NULL",
    oneLine: "NULL은 0이나 빈 문자열이 아니라 '값을 모름'이다.",
    why: "IS NULL, IS NOT NULL, 집계 함수 처리에서 헷갈린다.",
    memorize: "NULL 비교는 =가 아니라 IS NULL.",
    example: "WHERE name = NULL은 틀린 표현이고, WHERE name IS NULL을 써야 한다.",
    linked: "NULL이 나오면 일반 비교 연산자를 쓰지 않는다고 기억한다.",
    tags: ["SQL", "NULL", "조건"],
  },
  {
    id: "deep-code-001",
    heat: "MAX",
    title: "코드 출력 기본 풀이법",
    oneLine: "코드 출력은 머리로 찍는 문제가 아니라 변수표를 갱신하는 문제다.",
    why: "C, Java, Python 모두 결국 값이 어떻게 바뀌는지 묻는다.",
    memorize: "표를 만든다. 한 줄 실행한다. 값 바뀐 것만 적는다.",
    example: "x=3에서 x++는 먼저 3을 쓰고 나중에 x가 4가 된다.",
    linked: "모든 코드 문제의 첫 단계로 변수표를 만든다.",
    tags: ["코드", "출력", "풀이법"],
  },
  {
    id: "deep-c-001",
    heat: "MAX",
    title: "C 포인터",
    oneLine: "포인터는 값 자체가 아니라 값이 있는 주소를 들고 있는 변수다.",
    why: "C 문제에서 가장 자주 사람을 넘어뜨리는 부분이다.",
    memorize: "&는 주소, *는 그 주소 안의 값.",
    example: "int x=5; int *p=&x; 라면 *p는 5다.",
    linked: "포인터 문제는 p가 어디를 가리키는지 화살표로 그린다.",
    tags: ["C", "포인터", "주소"],
  },
  {
    id: "deep-c-002",
    heat: "MAX",
    title: "C 배열과 포인터",
    oneLine: "배열 이름은 첫 번째 원소 주소처럼 다룰 수 있다.",
    why: "*(p+2), a[2], p[2] 같은 표현이 자주 나온다.",
    memorize: "a[i]는 *(a+i)와 비슷하게 생각한다.",
    example: "int a[]={10,20,30}; int *p=a; *(p+1)은 20이다.",
    linked: "인덱스가 0부터 시작한다는 것을 절대 잊지 않는다.",
    tags: ["C", "배열", "포인터"],
  },
  {
    id: "deep-c-003",
    heat: "HIGH",
    title: "C 증감 연산자",
    oneLine: "x++는 먼저 쓰고 증가, ++x는 먼저 증가하고 쓴다.",
    why: "짧은 출력 문제로 자주 나온다.",
    memorize: "뒤에 붙으면 뒤늦게, 앞에 붙으면 앞서서.",
    example: "x=3일 때 x++은 3을 사용한 뒤 x가 4가 된다.",
    linked: "증감 연산은 한 줄 안에서 값을 쓰는 순서를 적는다.",
    tags: ["C", "증감연산", "출력"],
  },
  {
    id: "deep-c-004",
    heat: "HIGH",
    title: "C 문자열",
    oneLine: "C 문자열은 문자 배열이고 끝에 널 문자 '\\0'이 숨어 있다.",
    why: "strlen, 문자 인덱스, 문자 코드 계산이 나온다.",
    memorize: "문자열 길이는 보이는 글자 수, 배열 크기는 널 문자까지 생각.",
    example: "char s[]=\"ABC\"; 는 A, B, C, \\0 네 칸이 필요하다.",
    linked: "문자열 문제는 인덱스와 널 문자를 조심한다.",
    tags: ["C", "문자열", "배열"],
  },
  {
    id: "deep-c-005",
    heat: "MID",
    title: "C 구조체",
    oneLine: "구조체는 여러 값을 하나의 묶음으로 만든 사용자 정의 자료형이다.",
    why: "멤버 접근 연산자 . 과 -> 를 묻는다.",
    memorize: "변수는 점, 포인터는 화살표.",
    example: "s.age는 구조체 변수 접근, p->age는 구조체 포인터 접근이다.",
    linked: "문제에 struct와 포인터가 함께 나오면 ->를 찾는다.",
    tags: ["C", "구조체", "포인터"],
  },
  {
    id: "deep-java-001",
    heat: "MAX",
    title: "오버로딩과 오버라이딩",
    oneLine: "오버로딩은 같은 이름 다른 매개변수, 오버라이딩은 부모 메서드를 자식이 다시 쓰는 것이다.",
    why: "Java 출력 문제에서 자주 섞인다.",
    memorize: "로딩은 매개변수, 라이딩은 상속 재정의.",
    example: "print(int)와 print(String)은 오버로딩이고, 자식이 부모의 run을 다시 만들면 오버라이딩이다.",
    linked: "호출될 메서드를 찾을 때 둘을 먼저 구분한다.",
    tags: ["Java", "오버로딩", "오버라이딩"],
  },
  {
    id: "deep-java-002",
    heat: "HIGH",
    title: "Java 동적 바인딩",
    oneLine: "오버라이딩 메서드는 변수 타입보다 실제 객체 타입 기준으로 실행된다.",
    why: "부모 변수에 자식 객체를 넣는 코드가 자주 나온다.",
    memorize: "new 뒤에 나온 진짜 객체를 봐라.",
    example: "Animal a = new Dog(); a.sound(); 는 Dog의 sound가 실행된다.",
    linked: "Java 출력 문제에서 new 오른쪽을 동그라미 친다.",
    tags: ["Java", "상속", "동적바인딩"],
  },
  {
    id: "deep-java-003",
    heat: "HIGH",
    title: "static",
    oneLine: "static은 객체별이 아니라 클래스 전체가 공유하는 것이다.",
    why: "객체를 여러 개 만들어도 static 값이 같이 변하는 문제로 나온다.",
    memorize: "static은 공동 지갑.",
    example: "모든 학생 객체가 같은 schoolName static 변수를 공유할 수 있다.",
    linked: "static 변수가 나오면 객체별로 따로 적지 말고 하나만 적는다.",
    tags: ["Java", "static", "클래스"],
  },
  {
    id: "deep-java-004",
    heat: "MID",
    title: "== 과 equals",
    oneLine: "==는 주소 비교, equals는 보통 내용 비교다.",
    why: "문자열과 배열 비교에서 자주 틀린다.",
    memorize: "쌍등호는 같은 집에 사는지, equals는 얼굴이 같은지.",
    example: "new String(\"A\") == new String(\"A\")는 보통 false, equals는 true다.",
    linked: "Java 비교 문제는 참조와 내용을 나눠 본다.",
    tags: ["Java", "equals", "참조"],
  },
  {
    id: "deep-python-001",
    heat: "MAX",
    title: "Python 슬라이싱",
    oneLine: "슬라이싱은 [시작:끝직전:간격]이다.",
    why: "짧고 내기 좋아서 Python 출력 문제에 자주 나온다.",
    memorize: "끝은 포함하지 않는다. 음수 간격은 뒤로 간다.",
    example: "'ABCDE'[1:4]는 BCD이고, [::-1]은 뒤집기다.",
    linked: "인덱스를 글자 위에 0부터 써 놓고 푼다.",
    tags: ["Python", "슬라이싱", "문자열"],
  },
  {
    id: "deep-python-002",
    heat: "HIGH",
    title: "Python 리스트 메서드",
    oneLine: "append는 하나를 뒤에 붙이고, extend는 여러 값을 풀어서 붙인다.",
    why: "append, pop, reverse, sort 같은 메서드가 출력 문제로 나온다.",
    memorize: "append 하나, extend 펼침, pop 꺼내고 삭제, reverse 뒤집기.",
    example: "a=[1,2]; a.append([3,4])는 [1,2,[3,4]]가 된다.",
    linked: "리스트 문제는 원본이 바뀌는지 새 값이 생기는지 본다.",
    tags: ["Python", "리스트", "메서드"],
  },
  {
    id: "deep-algo-001",
    heat: "MID",
    title: "재귀",
    oneLine: "재귀는 함수가 자기 자신을 다시 부르는 것이다.",
    why: "팩토리얼, 피보나치, 출력 순서 문제가 나온다.",
    memorize: "멈추는 조건이 없으면 끝없이 돈다.",
    example: "factorial(n)은 n * factorial(n-1)로 만들 수 있고 n==1에서 멈춘다.",
    linked: "재귀 문제는 호출이 쌓이고 되돌아오며 계산된다는 것을 그린다.",
    tags: ["알고리즘", "재귀", "코드"],
  },
  {
    id: "deep-algo-002",
    heat: "MID",
    title: "스택과 큐",
    oneLine: "스택은 나중에 넣은 것이 먼저 나오고, 큐는 먼저 넣은 것이 먼저 나온다.",
    why: "자료구조 기본 단답으로 나온다.",
    memorize: "스택은 접시 쌓기 LIFO, 큐는 줄서기 FIFO.",
    example: "브라우저 뒤로 가기는 스택, 프린터 대기열은 큐다.",
    linked: "LIFO/FIFO 약어와 함께 외운다.",
    tags: ["자료구조", "스택", "큐"],
  },
  {
    id: "deep-os-001",
    heat: "HIGH",
    title: "프로세스와 스레드",
    oneLine: "프로세스는 실행 중인 프로그램, 스레드는 프로세스 안의 작은 실행 흐름이다.",
    why: "운영체제 기본 용어로 자주 나온다.",
    memorize: "프로세스는 집, 스레드는 집 안에서 일하는 사람.",
    example: "브라우저 프로세스 안에서 화면 표시 스레드와 다운로드 스레드가 같이 돌 수 있다.",
    linked: "자원 소유는 프로세스, 실행 단위는 스레드로 기억한다.",
    tags: ["OS", "프로세스", "스레드"],
  },
  {
    id: "deep-os-002",
    heat: "HIGH",
    title: "스케줄링",
    oneLine: "스케줄링은 CPU를 어떤 프로세스에게 줄지 정하는 것이다.",
    why: "FCFS, SJF, RR, SRT가 계산형과 단답형으로 나온다.",
    memorize: "FCFS 먼저 온 순서, SJF 짧은 작업 먼저, RR 시간 나눠 돌림, SRT 남은 시간 짧은 것 먼저.",
    example: "시간 할당량을 주고 돌아가며 실행하면 Round Robin이다.",
    linked: "스케줄링 문제는 선점형인지 비선점형인지도 같이 본다.",
    tags: ["OS", "스케줄링", "CPU"],
  },
  {
    id: "deep-os-003",
    heat: "HIGH",
    title: "교착상태",
    oneLine: "교착상태는 서로 자원을 붙잡고 기다리느라 아무도 못 움직이는 상태다.",
    why: "4가지 필요조건을 묻는 문제가 잘 나온다.",
    memorize: "상호배제, 점유와 대기, 비선점, 환형대기.",
    example: "A는 프린터를 잡고 스캐너를 기다리고, B는 스캐너를 잡고 프린터를 기다리면 교착상태다.",
    linked: "4조건 중 하나라도 깨면 예방할 수 있다.",
    tags: ["OS", "교착상태", "Deadlock"],
  },
  {
    id: "deep-os-004",
    heat: "HIGH",
    title: "페이지 교체",
    oneLine: "페이지 교체는 메모리가 꽉 찼을 때 어떤 페이지를 내보낼지 정하는 것이다.",
    why: "LRU, LFU, FIFO는 반복 출제되는 약어다.",
    memorize: "LRU 오래 안 씀, LFU 적게 씀, FIFO 먼저 들어온 것.",
    example: "가장 오래 참조되지 않은 페이지를 빼면 LRU다.",
    linked: "약어 뜻이 곧 풀이법이다.",
    tags: ["OS", "페이지교체", "LRU"],
  },
  {
    id: "deep-linux-001",
    heat: "HIGH",
    title: "Linux 권한",
    oneLine: "Linux 권한은 읽기 r=4, 쓰기 w=2, 실행 x=1을 더해서 표현한다.",
    why: "chmod 숫자 계산 문제가 나온다.",
    memorize: "rwx는 7, r-x는 5, --x는 1.",
    example: "rwx r-x --x는 751이다.",
    linked: "권한 문제는 사용자/그룹/기타 순서로 세 칸을 계산한다.",
    tags: ["Linux", "chmod", "권한"],
  },
  {
    id: "deep-net-001",
    heat: "HIGH",
    title: "OSI 7계층",
    oneLine: "OSI 7계층은 네트워크 통신을 7층으로 나눈 설명 모델이다.",
    why: "장비와 프로토콜 계층을 묻는 문제가 나온다.",
    memorize: "물데네전세표응. 물리, 데이터링크, 네트워크, 전송, 세션, 표현, 응용.",
    example: "IP는 네트워크 계층, TCP는 전송 계층, HTTP는 응용 계층이다.",
    linked: "프로토콜이 나오면 몇 계층인지 떠올린다.",
    tags: ["네트워크", "OSI", "계층"],
  },
  {
    id: "deep-net-002",
    heat: "MAX",
    title: "TCP와 UDP",
    oneLine: "TCP는 믿을 수 있게 보내고, UDP는 빠르게 보낸다.",
    why: "전송 계층 비교는 단골이다.",
    memorize: "TCP 연결형 신뢰성, UDP 비연결 빠름.",
    example: "파일 전송은 TCP가 어울리고, 실시간 스트리밍은 UDP가 쓰일 수 있다.",
    linked: "신뢰성, 흐름제어, 오류제어가 나오면 TCP를 떠올린다.",
    tags: ["네트워크", "TCP", "UDP"],
  },
  {
    id: "deep-net-003",
    heat: "MAX",
    title: "IP 주소와 서브넷",
    oneLine: "IP 주소는 네트워크에서 컴퓨터를 찾는 주소이고, 서브넷은 그 주소를 더 작게 나눈 구역이다.",
    why: "CIDR 계산은 기출 변형으로 계속 나올 수 있다.",
    memorize: "/24는 255.255.255.0, /23은 255.255.254.0, /22는 255.255.252.0.",
    example: "192.168.11.20/23은 192.168.10.0 네트워크에 속한다.",
    linked: "서브넷은 블록 크기만 잡으면 풀린다.",
    tags: ["네트워크", "CIDR", "서브넷"],
  },
  {
    id: "deep-net-004",
    heat: "HIGH",
    title: "라우팅 프로토콜",
    oneLine: "라우팅 프로토콜은 패킷이 어느 길로 갈지 정하게 도와준다.",
    why: "OSPF, RIP, BGP 같은 약어가 단답으로 나온다.",
    memorize: "RIP는 홉 수, OSPF는 링크 상태, BGP는 AS 사이.",
    example: "최단 경로를 링크 상태 기반으로 계산하는 것은 OSPF다.",
    linked: "라우팅은 기준이 홉 수인지 링크 상태인지 본다.",
    tags: ["네트워크", "라우팅", "OSPF"],
  },
  {
    id: "deep-net-005",
    heat: "HIGH",
    title: "NAT",
    oneLine: "NAT는 사설 IP와 공인 IP를 바꿔주는 기술이다.",
    why: "공인 IP 부족, 내부망 보호와 함께 자주 나온다.",
    memorize: "집 안 주소를 인터넷 주소로 바꿔 나간다.",
    example: "집의 여러 기기가 하나의 공유기 공인 IP로 인터넷에 접속하는 것이 NAT의 예다.",
    linked: "주소 변환이라는 말이 나오면 NAT다.",
    tags: ["네트워크", "NAT", "IP"],
  },
  {
    id: "deep-net-006",
    heat: "MID",
    title: "DNS와 DHCP",
    oneLine: "DNS는 이름을 IP로 바꾸고, DHCP는 IP를 자동으로 나눠준다.",
    why: "네트워크 서비스 약어 문제로 나온다.",
    memorize: "DNS는 전화번호부, DHCP는 자동 주소 배급.",
    example: "naver.com을 IP로 찾는 것은 DNS, 노트북이 자동 IP를 받는 것은 DHCP다.",
    linked: "이름 변환과 자동 할당을 구분한다.",
    tags: ["네트워크", "DNS", "DHCP"],
  },
  {
    id: "deep-net-007",
    heat: "HIGH",
    title: "HDLC",
    oneLine: "HDLC는 데이터 링크 계층의 비트 중심 전송 제어 프로토콜이다.",
    why: "2026년 1회 공개 복원 범위에서 I/S/U 프레임과 모드가 보인다.",
    memorize: "I는 정보, S는 감독, U는 비번호 제어.",
    example: "실제 사용자 데이터를 보내는 프레임은 I-frame이다.",
    linked: "HDLC는 프레임 종류와 ABM/ARM 같은 모드를 같이 외운다.",
    tags: ["네트워크", "HDLC", "프레임"],
  },
  {
    id: "deep-sec-001",
    heat: "MAX",
    title: "대칭키와 공개키",
    oneLine: "대칭키는 같은 키로 잠그고 열고, 공개키는 공개키와 개인키 한 쌍을 쓴다.",
    why: "AES와 RSA 구분은 보안 기본 점수다.",
    memorize: "AES는 대칭키, RSA는 공개키.",
    example: "빠른 대량 암호화는 AES, 키 교환이나 전자서명은 RSA가 자주 언급된다.",
    linked: "암호 알고리즘 이름이 나오면 대칭/비대칭/해시로 먼저 나눈다.",
    tags: ["보안", "AES", "RSA"],
  },
  {
    id: "deep-sec-002",
    heat: "HIGH",
    title: "해시",
    oneLine: "해시는 어떤 데이터를 고정 길이 지문처럼 바꾸는 것이다.",
    why: "SHA, 무결성, 비밀번호 저장 문제에 나온다.",
    memorize: "해시는 복호화가 아니라 확인용 지문.",
    example: "파일이 바뀌었는지 확인하려고 SHA 해시값을 비교할 수 있다.",
    linked: "복호화라는 말이 나오면 해시가 아니라는 점을 조심한다.",
    tags: ["보안", "SHA", "해시"],
  },
  {
    id: "deep-sec-003",
    heat: "HIGH",
    title: "전자서명",
    oneLine: "전자서명은 보낸 사람이 진짜인지, 내용이 안 바뀌었는지 확인하게 해준다.",
    why: "인증, 무결성, 부인방지 키워드로 나온다.",
    memorize: "전자서명은 인증, 무결성, 부인방지.",
    example: "계약 문서에 전자서명을 하면 나중에 보낸 사실을 부인하기 어렵다.",
    linked: "부인방지라는 말이 나오면 전자서명을 떠올린다.",
    tags: ["보안", "전자서명", "인증"],
  },
  {
    id: "deep-sec-004",
    heat: "MAX",
    title: "인증과 인가",
    oneLine: "인증은 너 누구냐, 인가는 너 이거 해도 되냐다.",
    why: "OAuth, JWT, SSO와 함께 많이 나온다.",
    memorize: "로그인=인증, 권한 확인=인가.",
    example: "아이디와 비밀번호로 로그인하는 것은 인증이고, 관리자 페이지 접근 허용은 인가다.",
    linked: "권한 위임은 OAuth, 토큰은 JWT, 한 번 로그인은 SSO.",
    tags: ["보안", "인증", "인가"],
  },
  {
    id: "deep-sec-005",
    heat: "HIGH",
    title: "SQL Injection",
    oneLine: "SQL Injection은 입력값에 SQL 조각을 넣어 DB 명령을 속이는 공격이다.",
    why: "웹 보안 공격 중 가장 자주 나오는 축이다.",
    memorize: "입력값이 SQL문이 되어버리면 SQL Injection.",
    example: "로그인 입력칸에 ' OR '1'='1 같은 값을 넣어 조건을 속이는 식이다.",
    linked: "대응은 Prepared Statement, 입력 검증, 권한 최소화다.",
    tags: ["보안", "SQL Injection", "웹취약점"],
  },
  {
    id: "deep-sec-006",
    heat: "HIGH",
    title: "XSS",
    oneLine: "XSS는 웹 페이지에 악성 스크립트를 심어 사용자 브라우저에서 실행시키는 공격이다.",
    why: "SQL Injection과 함께 웹 보안 단골이다.",
    memorize: "스크립트가 남의 브라우저에서 실행되면 XSS.",
    example: "댓글에 script 태그를 넣어 다른 사용자의 쿠키를 탈취하려는 공격이다.",
    linked: "대응은 출력 인코딩, 입력 검증, 쿠키 HttpOnly 설정이다.",
    tags: ["보안", "XSS", "웹취약점"],
  },
  {
    id: "deep-sec-007",
    heat: "HIGH",
    title: "CSRF",
    oneLine: "CSRF는 로그인된 사용자를 속여 원하지 않는 요청을 보내게 하는 공격이다.",
    why: "XSS와 헷갈리기 좋다.",
    memorize: "사용자가 모르게 요청이 날아가면 CSRF.",
    example: "로그인된 상태에서 악성 링크를 눌러 비밀번호 변경 요청이 전송되는 식이다.",
    linked: "대응은 CSRF 토큰, SameSite 쿠키, Referer 검증이다.",
    tags: ["보안", "CSRF", "웹취약점"],
  },
  {
    id: "deep-sec-008",
    heat: "MID",
    title: "IDS, IPS, 방화벽",
    oneLine: "방화벽은 막고, IDS는 탐지하고, IPS는 탐지 후 차단한다.",
    why: "보안 장비 역할 구분 문제로 나온다.",
    memorize: "D는 Detect 탐지, P는 Prevent 방지.",
    example: "공격 패턴을 발견해 관리자에게 알리면 IDS, 바로 막으면 IPS다.",
    linked: "역할 동사를 보고 장비를 고른다.",
    tags: ["보안", "IDS", "IPS"],
  },
  {
    id: "deep-test-001",
    heat: "HIGH",
    title: "화이트박스와 블랙박스 테스트",
    oneLine: "화이트박스는 내부 코드를 보고, 블랙박스는 내부를 안 보고 입출력만 본다.",
    why: "테스트 기법 분류 문제가 반복된다.",
    memorize: "속을 보면 화이트, 겉만 보면 블랙.",
    example: "분기 커버리지는 화이트박스, 동등분할은 블랙박스다.",
    linked: "커버리지라는 말이 나오면 화이트박스 쪽이다.",
    tags: ["테스트", "화이트박스", "블랙박스"],
  },
  {
    id: "deep-test-002",
    heat: "MAX",
    title: "커버리지",
    oneLine: "커버리지는 테스트가 코드의 어느 부분까지 실행했는지 재는 기준이다.",
    why: "문장, 분기, 조건, 경로 커버리지가 정의형으로 나온다.",
    memorize: "문장=모든 줄, 분기=참/거짓, 조건=개별 조건, 경로=가능한 흐름.",
    example: "if문의 true와 false를 모두 지나가면 분기 커버리지를 만족한다.",
    linked: "문장과 분기는 특히 자주 나온다.",
    tags: ["테스트", "커버리지", "화이트박스"],
  },
  {
    id: "deep-test-003",
    heat: "HIGH",
    title: "정적 분석과 동적 분석",
    oneLine: "정적 분석은 실행하지 않고 보고, 동적 분석은 실행하면서 본다.",
    why: "2022년 공개 복원 범위에서도 보이는 기본 개념이다.",
    memorize: "정적은 멈춰서 보기, 동적은 돌려서 보기.",
    example: "코드 리뷰는 정적 분석, 메모리 누수 추적은 동적 분석이다.",
    linked: "실행 여부만 보면 된다.",
    tags: ["테스트", "정적분석", "동적분석"],
  },
  {
    id: "deep-test-004",
    heat: "MID",
    title: "단위, 통합, 시스템, 인수 테스트",
    oneLine: "작은 부품부터 전체 제품, 고객 확인까지 단계별로 테스트한다.",
    why: "테스트 단계 순서 문제가 나온다.",
    memorize: "단통시인. 단위, 통합, 시스템, 인수.",
    example: "함수 하나 검사=단위, 모듈끼리 연결 검사=통합, 전체 시스템 검사=시스템, 고객 확인=인수.",
    linked: "순서와 주체를 같이 기억한다.",
    tags: ["테스트", "단계", "인수테스트"],
  },
  {
    id: "deep-int-001",
    heat: "HIGH",
    title: "REST",
    oneLine: "REST는 URI로 자원을 표현하고 HTTP 메서드로 행동을 표현하는 방식이다.",
    why: "인터페이스 구현 문제에서 자주 나온다.",
    memorize: "자원은 URI, 행동은 GET/POST/PUT/DELETE.",
    example: "GET /users/1은 1번 사용자를 조회한다는 뜻으로 볼 수 있다.",
    linked: "HTTP 메서드와 JSON이 같이 나오면 REST를 의심한다.",
    tags: ["인터페이스", "REST", "API"],
  },
  {
    id: "deep-int-002",
    heat: "MID",
    title: "JSON과 XML",
    oneLine: "JSON과 XML은 시스템끼리 데이터를 주고받을 때 쓰는 표현 형식이다.",
    why: "데이터 형식 비교 문제가 나온다.",
    memorize: "JSON은 가볍고 JavaScript 객체처럼 생김, XML은 태그 중심.",
    example: "{\"name\":\"kim\"}은 JSON, <name>kim</name>은 XML이다.",
    linked: "괄호와 콜론이면 JSON, 태그면 XML.",
    tags: ["인터페이스", "JSON", "XML"],
  },
  {
    id: "deep-int-003",
    heat: "MID",
    title: "EAI와 ESB",
    oneLine: "EAI와 ESB는 여러 시스템을 연결하는 통합 방식이다.",
    why: "통합 구현 단답으로 나온다.",
    memorize: "EAI는 기업 애플리케이션 통합, ESB는 버스처럼 중간에서 연결.",
    example: "인사, 회계, 물류 시스템 데이터를 한 흐름으로 묶는 것이 통합 구현이다.",
    linked: "기업 내부 시스템 연계라는 말이 나오면 EAI/ESB를 본다.",
    tags: ["통합구현", "EAI", "ESB"],
  },
  {
    id: "deep-server-001",
    heat: "MID",
    title: "MVC",
    oneLine: "MVC는 Model, View, Controller로 역할을 나누는 구조다.",
    why: "서버 프로그램 구현과 화면 흐름에서 나온다.",
    memorize: "Model 데이터, View 화면, Controller 조정.",
    example: "사용자 요청을 Controller가 받고, Model에서 데이터를 가져와, View로 보여준다.",
    linked: "역할 분리와 유지보수 키워드가 나오면 MVC를 떠올린다.",
    tags: ["서버", "MVC", "아키텍처"],
  },
  {
    id: "deep-server-002",
    heat: "MID",
    title: "공통 모듈",
    oneLine: "공통 모듈은 여러 기능에서 반복해서 쓰는 코드를 따로 만든 것이다.",
    why: "재사용성, 유지보수성, 결합도/응집도와 연결된다.",
    memorize: "반복되면 공통으로 뺀다.",
    example: "로그인 확인, 날짜 포맷, 파일 업로드 같은 기능을 공통 모듈로 둘 수 있다.",
    linked: "재사용과 중복 제거라는 말이 나오면 공통 모듈을 떠올린다.",
    tags: ["서버", "모듈", "재사용"],
  },
  {
    id: "deep-devops-001",
    heat: "MID",
    title: "Git과 형상관리",
    oneLine: "형상관리는 소스와 문서의 변경 이력을 관리하는 것이다.",
    why: "Git, 버전관리, 변경관리 단답으로 나온다.",
    memorize: "언제, 누가, 무엇을 바꿨는지 관리한다.",
    example: "Git으로 commit을 남기면 이전 버전으로 돌아가거나 변경 내용을 비교할 수 있다.",
    linked: "버전, 변경, 이력이라는 말이 나오면 형상관리.",
    tags: ["형상관리", "Git", "버전관리"],
  },
  {
    id: "deep-devops-002",
    heat: "MID",
    title: "CI/CD",
    oneLine: "CI/CD는 코드를 자주 합치고 자동으로 빌드, 테스트, 배포하는 흐름이다.",
    why: "실무형 개발 프로세스 용어로 나온다.",
    memorize: "CI는 자주 통합, CD는 자동 배포 쪽.",
    example: "코드를 push하면 자동 테스트가 돌고 서버에 배포되는 흐름이다.",
    linked: "자동화, 빌드, 테스트, 배포가 함께 나오면 CI/CD.",
    tags: ["DevOps", "CI/CD", "배포"],
  },
  {
    id: "deep-pack-001",
    heat: "MID",
    title: "릴리즈 노트",
    oneLine: "릴리즈 노트는 새 버전에 무엇이 바뀌었는지 알려주는 문서다.",
    why: "제품소프트웨어 패키징 영역에서 자주 나온다.",
    memorize: "버전, 변경사항, 개선사항, 알려진 문제.",
    example: "1.2.0 버전에서 로그인 오류 수정, 성능 개선, 주의사항을 적어 배포한다.",
    linked: "배포 문서 문제에서 릴리즈 노트를 떠올린다.",
    tags: ["패키징", "릴리즈노트", "배포"],
  },
  {
    id: "deep-pack-002",
    heat: "MID",
    title: "DRM",
    oneLine: "DRM은 디지털 콘텐츠의 사용 권한을 관리하고 불법 복제를 막는 기술이다.",
    why: "패키징과 저작권 보호 단답으로 나온다.",
    memorize: "Digital Rights Management, 디지털 권리 관리.",
    example: "전자책을 구매한 계정에서만 읽게 제한하는 것이 DRM의 예다.",
    linked: "저작권, 사용 권한, 불법 복제 방지라는 말이 나오면 DRM.",
    tags: ["패키징", "DRM", "저작권"],
  },
  {
    id: "deep-new-001",
    heat: "MID",
    title: "클라우드",
    oneLine: "클라우드는 서버와 저장공간 같은 IT 자원을 인터넷으로 빌려 쓰는 방식이다.",
    why: "IaaS, PaaS, SaaS 분류가 나온다.",
    memorize: "IaaS는 인프라, PaaS는 개발 플랫폼, SaaS는 완성 소프트웨어.",
    example: "가상 서버는 IaaS, 앱 배포 플랫폼은 PaaS, 웹메일은 SaaS로 볼 수 있다.",
    linked: "무엇을 빌려 쓰는지 보고 I/P/S를 나눈다.",
    tags: ["신기술", "클라우드", "SaaS"],
  },
  {
    id: "deep-new-002",
    heat: "MID",
    title: "가상화와 컨테이너",
    oneLine: "가상화는 컴퓨터 안에 가짜 컴퓨터를 만들고, 컨테이너는 앱 실행 환경을 가볍게 묶는다.",
    why: "클라우드, DevOps와 연결되어 나온다.",
    memorize: "VM은 무겁지만 독립적, 컨테이너는 가볍고 빠름.",
    example: "Docker는 컨테이너 기술의 대표 예다.",
    linked: "배포 환경을 똑같이 맞춘다는 말이 나오면 컨테이너를 떠올린다.",
    tags: ["신기술", "가상화", "컨테이너"],
  },
  {
    id: "deep-new-003",
    heat: "MID",
    title: "마이크로서비스",
    oneLine: "마이크로서비스는 큰 서비스를 작은 서비스 여러 개로 나눠 독립적으로 개발, 배포하는 구조다.",
    why: "현대 시스템 아키텍처 용어로 출제될 수 있다.",
    memorize: "작게 나누고, 따로 배포하고, API로 연결한다.",
    example: "회원, 주문, 결제를 각각 독립 서비스로 운영하는 구조다.",
    linked: "독립 배포, 작은 서비스, API 통신이라는 말이 나오면 MSA.",
    tags: ["아키텍처", "MSA", "서비스"],
  },
  {
    id: "deep-ai-001",
    heat: "MID",
    title: "데이터 마이닝과 빅데이터",
    oneLine: "데이터 마이닝은 많은 데이터에서 의미 있는 패턴을 찾는 것이다.",
    why: "신기술 단답으로 간헐적으로 나온다.",
    memorize: "데이터 속 금을 캐는 느낌. 패턴 발견.",
    example: "구매 기록에서 함께 잘 팔리는 상품 조합을 찾는 것이 데이터 마이닝이다.",
    linked: "분석, 패턴, 대량 데이터라는 말이 나오면 떠올린다.",
    tags: ["신기술", "빅데이터", "데이터마이닝"],
  },
  {
    id: "deep-final-001",
    heat: "MAX",
    title: "단답 답안 작성법",
    oneLine: "정처기 실기 답안은 길게 설명하기보다 정확한 핵심어를 쓰는 것이 중요하다.",
    why: "아는 것도 길게 쓰다가 핵심어를 틀리면 점수가 안 나온다.",
    memorize: "약어는 정확히, 한글 용어는 교재식으로, SQL은 철자 정확히.",
    example: "중복 제거라고 길게 쓰기보다 DISTINCT라고 쓰는 문제가 있다.",
    linked: "이론을 읽을 때도 최종 답안에 쓸 단어를 따로 기억한다.",
    tags: ["시험전략", "단답", "답안"],
  },
  {
    id: "deep-final-002",
    heat: "MAX",
    title: "5일 이론 공부 순서",
    oneLine: "DB/SQL, 코드, 네트워크/OS, 보안/테스트, 전체 오답 순서가 가장 효율적이다.",
    why: "점수 비중과 반복 출제 빈도를 고려하면 앞의 세 덩어리가 합격의 뼈대다.",
    memorize: "DBSQL -> 코드 -> 네트워크OS -> 보안테스트 -> 오답.",
    example: "1일 차에 SQL 예약어와 정규화를 끝내고, 2일 차에 코드 출력만 몰아친다.",
    linked: "이론도 이 순서로 읽고, 문제도 같은 순서로 푼다.",
    tags: ["시험전략", "5일루틴", "합격전략"],
  },
];
